#Pour rappel, le contexte dans dockerfile.dev demarre là ou se trouve docker-compose.override.yml, soit Jootshub.
FROM node:20

# Étape 1 — Copier et compiler les types partagés
WORKDIR /packages
COPY ./packages .

# Etape Build the types
WORKDIR /packages/types
RUN npm install --verbose && npm run build && ls -la dist/

WORKDIR /joots-backend

# Étape 2 — Installer les dépendances du backend
COPY ./joots-backend/package*.json ./
RUN npm cache clean --force && npm install --verbose

# Étape 3 : copier le schéma et générer le client Prisma
COPY ./joots-backend/prisma ./prisma
RUN npx prisma generate --schema=./prisma/schema.prisma

# Étape 4 : copier le reste
COPY ./joots-backend .

# Exposer le port Nest.js
EXPOSE 4000

# Activer le watch mode (supposant que tu as nest CLI installé localement)
CMD ["npm", "run", "start:dev"]
