services:
  frontend:
    build:
      context: ./joots-frontend
      dockerfile: Dockerfile
    depends_on:
      - backend
    networks:
      - joots-network

  backend:
    build:
      context: ./joots-backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
      - SEED_DB=true
    depends_on:
      - postgres
      - redis
    networks:
      - joots-network

  postgres:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - joots-network

  redis:
    image: redis:7
    restart: always
    networks:
      - joots-network

networks:
  joots-network:
    driver: bridge

volumes:
  postgres_data:
