services:
  frontend:
    build:
      context: .
      dockerfile: ./joots-frontend/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./joots-frontend/.env.production
    depends_on:
      - backend
    networks:
      - joots-network
    restart: always

  backend:
    build:
      context: .
      dockerfile: ./joots-backend/Dockerfile
    environment:
      - NODE_ENV=production
    env_file:
      - ./joots-backend/.env.production
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    networks:
      - joots-network
    restart: always

  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - joots-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U joots_user -d joots_db"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    restart: always
    volumes:
      - redis_data:/data
    networks:
      - joots-network

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.prod.conf:/etc/nginx/nginx.conf
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - ./nginx/logs:/var/log/nginx
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend
      - backend
    networks:
      - joots-network
    restart: always

networks:
  joots-network:
    driver: bridge

volumes:
  postgres_data:
  redis_data: