FROM node:20-alpine

# Étape 1 — Copier et compiler les types partagés
WORKDIR /packages/types
COPY ./packages/types .
RUN npm install --verbose && npm run build && ls -la dist/


WORKDIR /joots-frontend

# Étape 2 — Installer les dépendances du frontend
COPY joots-frontend/package*.json ./
RUN npm cache clean --force && npm install --verbose


# Étape 3 : copier le reste
COPY ./joots-frontend .

EXPOSE 3000

CMD ["npm", "run", "dev"]